### ISSUE TITLE
Icon warning when testing Tabs component with jest

### ISSUE THREAD

**Issue by ssnowicki** [vueComponent/ant-design-vue#3660]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
Vue 3.0.5, antdv 2.0.0-rc.9, jest 26.0.0

### Reproduction link
[http://localhost:3000](http://localhost:3000)

### Steps to reproduce
When a vue component that uses a-tabs is mounted in a jest .spec.js, the console will throw a warning about default icons in the a-tabs component's icons.

### What is expected?
No warning, tab icons work correctly.

### What is actually happening?
It seems that the default icons for the tab component have not been updated to use the new icon syntax in antdv 2x.

console.warn
[Vue warn]: Invalid prop: type check failed for prop "icon". Expected Object, got String with value "".
at <IconBase class="" icon="" primaryColor=undefined  ... >
at <AntdIcon class="ant-tabs-tab-next-icon-target" icon="" >
at <RightOutlined class="ant-tabs-tab-next-icon-target" >
at <ScrollableTabBarNode saveRef=fn<saveRef> getRef=fn<getRef> centered=false  ... >
at <TabBarRootNode saveRef=fn<saveRef> centered=false tabPosition="top"  ... >
at <Anonymous children=fn<children> >
at <ScrollableInkTabBar centered=false tabPosition="top" prefixCls="ant-tabs"  ... >
at <TabBar key="tabBar" defaultActiveKey="2" hideAdd=false  ... >
at <Tabs defaultActiveKey="2" hideAdd=false centered=false  ... >
at <ATabs default-active-key="2" >
at <Login ref="VTU_COMPONENT" >
at <VTUROOT>

at warn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:40:17)
at validateProp (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1800:13)
at validateProps (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1771:9)
at initProps (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1504:9)
at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6335:5)
at mountComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4083:9)
at processComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4059:17)

console.error
Warning: [@ant-design/icons-vue] icon should be icon definiton, but got

at warn (node_modules/@ant-design/icons-vue/es/utils.js:11:13)
at warning (node_modules/@ant-design/icons-vue/es/utils.js:15:3)
at render (node_modules/@ant-design/icons-vue/es/components/IconBase.js:45:3)
at renderComponentRoot (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:718:19)
at fn (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4158:53)
at effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:46:24)
at Object.effect (node_modules/@vue/reactivity/dist/reactivity.cjs.js:21:9)

---
Ran into it during unit tests. Does not occur on the actual page.

**Comment by ssnowicki** [comment]
Tried to reproduce here using Login.spec.js, but there seems to be an issue with codesandbox importing Vue in .spec.js files.

https://codesandbox.io/s/heuristic-neumann-bi5qk?file=/tests/Login.spec.js

This codesandbox issue is unrelated to this original antdv issue I'm reporting, but it is blocking me from reproducing.

**Comment by ssnowicki** [comment]
You can reproduce locally using this repo:
https://github.com/ssnowicki/antdv-jest-tab-icon-warning

Steps to reproduce:
1. npm install
2. jest Login

See jest's output in the terminal for the warning.

**Comment by ssnowicki** [comment]
There are links to reproduce now.
