### ISSUE TITLE
Error in render: "TypeError: Cannot read property 'propsData' of undefined"

### ISSUE THREAD

**Issue by kikong** [vueComponent/ant-design-vue#370]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Vue2 vueCLI=>3.2.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zrlr40m183)

### Steps to reproduce
1.not Full import for ant-design-vue compoments
2.import menu component in .vue file
3.run app ,then Error is throwen "Error in render: "TypeError: Cannot read property 'propsData' of undefined""

### What is expected?
work as "Full import " setting

### What is actually happening?
[Vue warn]: Error in render: "TypeError: Cannot read property 'propsData' of undefined"
found in
---> <SubPopupMenu>

<ConnectSubPopupMenu>

<ProxyConnectSubPopupMenu>

<StoreProvider>

<Menu>

<AMenu>

<App> at /src/App.vue

<Root>

TypeError: Cannot read property 'propsData' of undefined
at VueComponent.renderCommonMenuItem (https://zrlr40m183.codesandbox.io/node_modules/ant-design-vue/dist/antd.min.js:19:131758)

at VueComponent.renderMenuItem (https://zrlr40m183.codesandbox.io/node_modules/ant-design-vue/dist/antd.min.js:19:133023)

at eval (https://zrlr40m183.codesandbox.io/node_modules/ant-design-vue/dist/antd.min.js:19:133617)

at Array.map (<anonymous>)

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/6ym097kr4z
PS: 建议使用Vue.use(Menu)全局注册, 会自动为你注册Menu下子组件

**Comment by kikong** [comment]
> https://codesandbox.io/s/6ym097kr4z
> PS: 建议使用Vue.use(Menu)全局注册, 会自动为你注册Menu下子组件

ok,已经改用全局导入的方式
