### ISSUE TITLE
Ant-design-vue cannot run in projects based on vite-ssr

### ISSUE THREAD

**Issue by zct1989** [vueComponent/ant-design-vue#3997]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
window 10；chrome 90.0.4430.85；vue 3.0.8；vite 2.2.3

### Reproduction link
[https://github.com/zct1989/vite-ssr-demo](https://github.com/zct1989/vite-ssr-demo)

### Steps to reproduce
npm run dev

### What is expected?
正常运行

### What is actually happening?
运行后报错如下：

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/zhuchentong/Project/ssr-vue/node_modules/lodash-es/isPlainObject.js
require() of ES modules is not supported.
require() of /home/zhuchentong/Project/ssr-vue/node_modules/lodash-es/isPlainObject.js from /home/zhuchentong/Project/ssr-vue/node_modules/ant-design-vue/lib/_util/props-util/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename isPlainObject.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/zhuchentong/Project/ssr-vue/node_modules/lodash-es/package.json.
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/home/zhuchentong/Project/ssr-vue/node_modules/ant-design-vue/lib/_util/props-util/index.js:28:45)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Comment by zct1989** [comment]
#3983

**Comment by zct1989** [comment]
报错是通过`require`加载了`lodash-es`模块
在生成的cjs模块代码中引入了‘lodash-es’
建议应该在生成cjs模块时将 `import * from 'lodash-es/*'`  替换为`import * from 'lodash/*'`

**Comment by sendya** [comment]
you can try `import Antd from 'ant-design-vue/es';`

**Comment by NoeyNoi** [comment]
+1

**Comment by lyh959550459** [comment]
+1024

**Comment by zct1989** [comment]
我现在是临时在项目中添加了`postinstall`脚本来解决

1. `ant-design-vue/lib`中`require('lodash-es)`
2. `ant-design-vue/lib`中`require('@ant-design/icons-vue/ICON)`

https://github.com/zct1989/antdv-es-patch

**Comment by shi-lai-mu** [comment]
+1 我再nuxtjs中也遇到了此问题
