### ISSUE TITLE
site build failed

### ISSUE THREAD

**Issue by asdjgfr** [vueComponent/ant-design-vue#4714]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.0

### Environment
same issue in windows 10, Ubuntu 20.04.3 LTS , Mac OS 11.0.1

### Reproduction link
[https://next.antdv.com/docs/vue/introduce-cn](https://next.antdv.com/docs/vue/introduce-cn)

### Steps to reproduce
run `yarn site` and get errors:

``` shell

yarn run v1.22.11
$ yarn routes && ./node_modules/vite/bin/vite.js build site --base=https://next.antdv.com/
$ node site/scripts/genrateRoutes.js
> site/vite.config.ts:47:49: warning: "../components/style/color/colorPalette.less" should be marked as external for use with "require.resolve"
47 │ ...  hack: `true;@import "${require.resolve('../components/style/color/colorPalette.less')}";`,
╵                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> site/themeConfig.ts:9:45: warning: "../components/style/color/colorPalette.less" should be marked as external for use with "require.resolve"
9 │       hack: `true;@import "${require.resolve('../components/style/color/colorPalette.less')}";`,
╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /mnt/d/work/ant-design-vue/site/vite.config.ts
error during build:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /mnt/d/work/ant-design-vue/node_modules/slash/index.js
require() of ES modules is not supported.
require() of /mnt/d/work/ant-design-vue/node_modules/slash/index.js from /mnt/d/work/ant-design-vue/site/vite.config.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /mnt/d/work/ant-design-vue/node_modules/slash/package.json.

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12)
at Module.require (internal/modules/cjs/loader.js:961:19)
at require (internal/modules/cjs/helpers.js:92:18)
at Object.<anonymous> (/mnt/d/work/ant-design-vue/site/vite.config.ts:522:31)
at Module._compile (internal/modules/cjs/loader.js:1072:14)
at Object.require.extensions.<computed> [as .ts] (/mnt/d/work/ant-design-vue/node_modules/vite/dist/node/chunks/dep-36bf480c.js:77283:20)
at Module.load (internal/modules/cjs/loader.js:937:32)
at Function.Module._load (internal/modules/cjs/loader.js:778:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

run `yarn routes` success

### What is expected?
build success

### What is actually happening?
build failed

**Comment by ajuner** [comment]
slash -> 3.0
