### ISSUE TITLE
Some style variables of the customized theme are invalid

### ISSUE THREAD

**Issue by zzlit** [vueComponent/ant-design-vue#4760]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.0

### Environment
"vue": "^3.2.19","vite": "^2.5.2"

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/next/components/style/themes/default.less](https://github.com/vueComponent/ant-design-vue/blob/next/components/style/themes/default.less)

### Steps to reproduce
`vite.config.ts`设置：
```
    css: {
      preprocessorOptions: {
        less: {
          modifyVars: {
            // '@input-height-lg': '56px', // 这个不生效
            // '@label-required-color:': '#ff6333' // 这个报错了
          },
          javascriptEnabled: true
        }
      }
    }
```
```
[vite] Internal server error: E:/base-html/node_modules/ant-design-vue/es/form/style/index.less:124:10: Double colon
You tried to parse Less with the standard CSS parser; try again with the postcss-less parser
Plugin: vite:css
File: E:/base-html/node_modules/ant-design-vue/es/form/style/index.less
123|          color: @text-color-secondary;
124|
125|          .@{form-prefix-cls}-hide-required-mark & {
|           ^
126|            display: none;
127|          }
at Input.error (E:\base-html\node_modules\vite\node_modules\postcss\lib\input.js:123:16)
at Parser.doubleColon (E:\base-html\node_modules\vite\node_modules\postcss\lib\parser.js:531:22)
at Parser.colon (E:\base-html\node_modules\vite\node_modules\postcss\lib\parser.js:498:16)
at Parser.checkMissedSemicolon (E:\base-html\node_modules\vite\node_modules\postcss\lib\parser.js:543:22)
at Parser.decl (E:\base-html\node_modules\vite\node_modules\postcss\lib\parser.js:253:12)
at Parser.other (E:\base-html\node_modules\vite\node_modules\postcss\lib\parser.js:115:18)
at Parser.parse (E:\base-html\node_modules\vite\node_modules\postcss\lib\parser.js:59:16)
at parse (E:\base-html\node_modules\vite\node_modules\postcss\lib\parse.js:11:12)
at new LazyResult (E:\base-html\node_modules\vite\node_modules\postcss\lib\lazy-result.js:133:16)
at Processor.process (E:\base-html\node_modules\vite\node_modules\postcss\lib\processor.js:36:12)
```

### What is expected?
@input-height-lg未生效;
@label-required-color报错。

### What is actually happening?
正确显示。

**Comment by zzlit** [comment]
> modifyVars不需要写@

一样的都不行

**Comment by zkwolf** [comment]
给个复现？

**Comment by zzlit** [comment]
> 给个复现？
[bug-report.zip](https://github.com/vueComponent/ant-design-vue/files/7335468/bug-report.zip)
vite.config.js里面使用`unplugin-vue-components`会报上面的错误，不使用的话会报另外一种错误，可以试试

**Comment by zzlit** [comment]
> input-height-lg这个看了一下感觉应该不是控制input高度的

对，我也觉得，看了那个input的高度被定死了，所以我现在暂时用padding来控制，但是其他的不行

**Comment by zzlit** [comment]
> @label-required-color 不是 @label-required-color:

低级错误了...感谢！
