### ISSUE TITLE
error occurs only in production

### ISSUE THREAD

**Issue by Archieeeeee** [vueComponent/ant-design-vue#5027]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.15

### Environment
Windows 11

### Reproduction link
[https://github.com/Archieeeeee/vitedemoantd.git](https://github.com/Archieeeeee/vitedemoantd.git)

### Steps to reproduce
```
yarn
yarn run build
yarn run preview
#close the dialog and check the  console log
```

### What is expected?
no error

### What is actually happening?
```
vendor.54d4b1e6.js:1 ReferenceError: loginVisible is not defined
at d.onUpdate:visible.s.<computed>.s.<computed> (main.9eeda243.js:1:1306)
at Ba (vendor.54d4b1e6.js:1:46522)
at fr (vendor.54d4b1e6.js:1:46601)
at i8 (vendor.54d4b1e6.js:1:11718)
at Proxy.handleCancel (vendor.54d4b1e6.js:98:197667)
at Ba (vendor.54d4b1e6.js:1:46522)
at fr (vendor.54d4b1e6.js:1:46601)
at i8 (vendor.54d4b1e6.js:1:11718)
at x (vendor.54d4b1e6.js:88:3643)
at Ba (vendor.54d4b1e6.js:1:46522)
```

**Comment by tangjinzhou** [comment]
I don’t know what’s wrong with mixing setup, but obviously it has nothing to do with components
