### ISSUE TITLE
form input error

### ISSUE THREAD

**Issue by yuyang1004** [vueComponent/ant-design-vue#5177]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
3.0.0-beta.7 vue3

### Reproduction link
[https://next.antdv.com/components/input-cn](https://next.antdv.com/components/input-cn)

### Steps to reproduce
<template>
<a-form>
<a-form-item>
<a-input />
</a-form-item>
</a-form>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { Input } from 'ant-design-vue'

export default defineComponent({
name: 'Login',
components: { [Input.name]: Input },
setup() {
return {}
}
})
</script>

### What is expected?
正常访问

### What is actually happening?
runtime-dom.esm-bundler.js:219 Uncaught (in promise) DOMException: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
at patchDOMProp (http://localhost:8088/assets/js/chunk-vendors.js:65156:21)
at patchProp (http://localhost:8088/assets/js/chunk-vendors.js:65285:17)
at mountElement (http://localhost:8088/assets/js/chunk-vendors.js:60980:25)
at processElement (http://localhost:8088/assets/js/chunk-vendors.js:60952:13)
at patch (http://localhost:8088/assets/js/chunk-vendors.js:60872:21)
at componentEffect (http://localhost:8088/assets/js/chunk-vendors.js:61364:21)
at reactiveEffect (http://localhost:8088/assets/js/chunk-vendors.js:55623:24)
at effect (http://localhost:8088/assets/js/chunk-vendors.js:55598:9)
at setupRenderEffect (http://localhost:8088/assets/js/chunk-vendors.js:61329:89)
at mountComponent (http://localhost:8088/assets/js/chunk-vendors.js:61288:9)

**Comment by CNMathon** [comment]
@tangjinzhou In fact, I also encountered this problem in v3.0.0-beta.8. I think this is a blocker-level bug, because it seriously affects the normal use of antd.

**Comment by tangjinzhou** [comment]
update 3.2
