### ISSUE TITLE
Vite: Rollup failed to resolve form-item-rest

### ISSUE THREAD

**Issue by tengfei8382** [vueComponent/ant-design-vue#5216]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
window10, vue3.2.20, vite2.6.10

### Reproduction link
[localhost:8000](localhost:8000)

### Steps to reproduce
1. 在代码中引入FormItemRest组件并使用
2. 使用vite进行编译

### What is expected?
正常通过编译

### What is actually happening?
[vite]: Rollup failed to resolve import "C:/Users/Barry/workspace/weinventing/internal/sunrise/branches/v1/web_apps/node_modules/ant-design-vue/es/form-item-rest/style/index" from "src\views\dashboard\myTask\dailyRecord\MultiSelect.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "C:/Users/Barry/workspace/weinventing/internal/sunrise/branches/v1/web_apps/node_modules/ant-design-vue/es/form-item-rest/style/index" from "src\views\dashboard\myTask\dailyRecord\MultiSelect.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
at onRollupWarning (C:\Users\Barry\workspace\weinventing\internal\sunrise\branches\v1\web_apps\node_modules\vite\dist\node\chunks\dep-be032392.js:43269:19)
at onwarn (C:\Users\Barry\workspace\weinventing\internal\sunrise\branches\v1\web_apps\node_modules\vite\dist\node\chunks\dep-be032392.js:43053:13)
at Object.onwarn (C:\Users\Barry\workspace\weinventing\internal\sunrise\branches\v1\web_apps\node_modules\rollup\dist\shared\rollup.js:20515:13)
at ModuleLoader.handleResolveId (C:\Users\Barry\workspace\weinventing\internal\sunrise\branches\v1\web_apps\node_modules\rollup\dist\shared\rollup.js:19864:26)
at C:\Users\Barry\workspace\weinventing\internal\sunrise\branches\v1\web_apps\node_modules\rollup\dist\shared\rollup.js:19856:26
at processTicksAndRejections (node:internal/process/task_queues:96:5)

---
之前在使用 RangePicker时，会报出同样的错误，但是可以使用DatePicker.RangePicker去解决，但是这个组件不在Form下面，无法通过Form.FormItemRest去使用。

**Comment by tangjinzhou** [comment]
use
`Form.ItemRest` or` import {FormItemRest} from 'ant-design-vue'`

**Comment by tengfei8382** [comment]
> use `Form.ItemRest` or` import {FormItemRest} from 'ant-design-vue'`

import { FormItemRest } from 'ant-design-vue'; 这个方法不可行
试验后这样导入不会报错， import { FormItemRest } from 'ant-design-vue/es/form'
