### ISSUE TITLE
tsx 在 Popover 组件使用 content 插槽报错

### ISSUE THREAD

**Issue by az031120103** [vueComponent/ant-design-vue#6020]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
node v16.11.0
macos mojave 10.14.6

### Reproduction link
[https://github.com/az031120103/popover](https://github.com/az031120103/popover)

### Steps to reproduce
import {Popover} from 'ant-design-vue'

export default {
  setup() {
    return () => (
      <Popover
        vSlots={{
          content: '1111111'
        }}
        placement='right'
      >
        11
      </Popover>
    )
  }
}

### What is expected?
不报错，正常显示提示内容

### What is actually happening?
runtime-dom.esm-bundler.js:35 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
at parentNode (runtime-dom.esm-bundler.js:35:1)
at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5684:1)
at ReactiveEffect.run (reactivity.esm-bundler.js:185:1)
at instance.update (runtime-core.esm-bundler.js:5716:1)
at updateComponent (runtime-core.esm-bundler.js:5541:1)
at processComponent (runtime-core.esm-bundler.js:5474:1)
at patch (runtime-core.esm-bundler.js:5060:1)
at patchKeyedChildren (runtime-core.esm-bundler.js:5836:1)
at patchChildren (runtime-core.esm-bundler.js:5779:1)
at processFragment (runtime-core.esm-bundler.js:5459:1)

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/195375597-4ebfc93e-d611-44ba-9a18-80317b75700d.png)

**Comment by az031120103** [comment]
@tangjinzhou 你好，我这里报错

浏览器信息
Google Chrome
Version 106.0.5249.103 (Official Build) (x86_64)

![image](https://user-images.githubusercontent.com/6166283/195477478-1b1448e2-fd08-4dcc-bb24-7bc3c510d60f.png)
