### ISSUE TITLE
Use a-range-picker component to add extra footer, insert a-select selection box in renderExtraFooter causes error

### ISSUE THREAD

**Issue by BalotT** [vueComponent/ant-design-vue#6062]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
ant-design-vue@3.2.13; vue@3.2.37

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/e-wai-de-ye-jiao-ant-design-vue-3-2-12-forked-ueiyql?file=/src/demo.vue)

### Steps to reproduce
在使用a-range-picker组件的添加额外的页脚插槽中，使用a-select下拉组件后，日期面板无法展开，组件异常

### What is expected?
在使用a-range-picker组件的添加额外的页脚插槽中，可以使用下拉组件。

### What is actually happening?
OptionList.js:71 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
at getEnabledActiveIndex2 (OptionList.js:71:42)
at setup29 (OptionList.js:88:20)

**Comment by BalotT** [comment]
看源码中是vc-select中的的useSelectProps方法inject接收下拉数据时出现异常导致后续取值props.flattenOptions报错
![image](https://user-images.githubusercontent.com/34759263/198573719-9dcc25f9-e933-4c4f-a3ce-f265b7a4ece8.png)
