### ISSUE TITLE
Second package into a library, refer to custom hooks in vitepress and report an error

### ISSUE THREAD

**Issue by az031120103** [vueComponent/ant-design-vue#6157]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
macOS monterey 12.6
node 16.11.0
ant-design-vue 3.2.11

### Reproduction link
[https://github.com/az031120103/test](https://github.com/az031120103/test)

### Steps to reproduce
```
git clone https://github.com/az031120103/test.git
npm run dev:ui
npm run dev:docs
```

### What is expected?
正常显示

### What is actually happening?
Form 组件的自定义 hooks useConfigInject 报错：

```
useConfigInject.js:71 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getPrefixCls')
at __WEBPACK_DEFAULT_EXPORT__ (useConfigInject.js:71:1)
at setup (Form.js:118:43)
at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
at setupStatefulComponent (runtime-core.esm-bundler.js:7246:29)
at setupComponent (runtime-core.esm-bundler.js:7201:11)
at mountComponent (runtime-core.esm-bundler.js:5524:13)
at processComponent (runtime-core.esm-bundler.js:5499:17)
at patch (runtime-core.esm-bundler.js:5101:21)
at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5638:21)
at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
```

**Comment by Kchengz** [comment]
遇到同样的问题，以下两种引入方式出现问题
出现错误方式一：
`import Form from "ant-design-vue/lib/form"`
`import FormItem from "ant-design-vue/lib/form/FormItem"`

出现错误方式二：
`const Form = () => import("ant-design-vue/lib/form")`
`const FormItem = () => import("ant-design-vue/lib/form/FormItem")`


最后换成下面的引入方式就可以了：
`import { Form, FormItem } from "ant-design-vue";`
