### ISSUE TITLE
 ant-design-vue cannot be used in browser introduction mode according to the tutorial on the official website.

### ISSUE THREAD

**Issue by gsdukbh** [vueComponent/ant-design-vue#6508]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.19

### Environment
window 11,Chrome  112.0.5615.138 ,vue 3.2.47

### Reproduction link
[https://github.com/gsdukbh/issue/blob/main/ant-design-vue/3.2.19-TEST-bug.html](https://github.com/gsdukbh/issue/blob/main/ant-design-vue/3.2.19-TEST-bug.html)

### Steps to reproduce
Example：

```html

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>test</title>
<script src="https://cdn.jsdelivr.net/npm/vue@3.2.47/dist/vue.global.min.js"></script>
<script src="https://unpkg.com/dayjs/dayjs.min.js"></script>
<script src="https://unpkg.com/dayjs/plugin/customParseFormat.js"></script>
<script src="https://unpkg.com/dayjs/plugin/weekday.js"></script>
<script src="https://unpkg.com/dayjs/plugin/localeData.js"></script>
<script src="https://unpkg.com/dayjs/plugin/weekOfYear.js"></script>
<script src="https://unpkg.com/dayjs/plugin/weekYear.js"></script>
<script src="https://unpkg.com/dayjs/plugin/advancedFormat.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ant-design-vue@3.2.19/dist/antd.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ant-design-vue@3.2.19/dist/antd.min.css">
</head>
<body>
<div id="app">{{ message }}
<a-button type="primary">Primary Button</a-button>
</div>

</body>
<script >

Vue.createApp({
data() {
return {
message: 'Hello Vue.js!'
}
}
}).mount('#app');

</script>

</html>
```

### What is expected?
Normal display Button component,

### What is actually happening?
Only the text of the button is displayed,

Console tips：
```txt
caught TypeError: Cannot read properties of undefined (reading '$i')
at w.extend (dayjs.min.js:1:6557)
at 9502 (dayjs.ts:16:1)
at d (bootstrap:19:22)
at 4449 (index.js:3:18)
at d (bootstrap:19:22)
at startup:4:27
at universalModuleDefinition:11:1
at universalModuleDefinition:9:18
at universalModuleDefinition:1:1

```

**Comment by tangjinzhou** [comment]
add `<script src="https://unpkg.com/dayjs/plugin/quarterOfYear.js"></script>`
