### ISSUE TITLE
vee-validate with tooltip input

### ISSUE THREAD

**Issue by op13op** [vueComponent/ant-design-vue#702]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
osx mojave 10.14.4, chrome v73.0, vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zx4kknz8jm)

### Steps to reproduce
```javascript
  <ValidationProvider :vid="vid" :name="$attrs.label" :rules="rules">
    <a-form-item
      slot-scope="{ errors, flags }"
      :label="$attrs.label"
      hasFeedback
      :validateStatus="resolveState({ errors, flags })"
      :help='errors[0]'
    >
      <a-tooltip>
         <template slot="title">
           test tooltip input
         </template>
        <a-input type="$attrs.type" :placeholder='$attrs.placeholder' v-model="innerValue" />
      </a-tooltip>
    </a-form-item>  
  </ValidationProvider>
```

### What is expected?
work properly with vee-validate

### What is actually happening?
```
[Vue warn]: Error in v-on handler: "TypeError: _this7.createTwoChains(...) is not a function"


found in


---> <AInput>

       <Anonymous>

         <Trigger>

           <Anonymous>

             <ATooltip>

               <ACol>

                 <ARow>

                   <AFormItem>

                     <ValidationProvider>

                       <InputWithValidation> at /src/components/inputs/InputWithValidation.vue

                         <AForm>

                           <ValidationObserver>

                             <RefactoredForm> at /src/components/RefactoredForm.vue

                               <App> at /src/App.vue

                                 <Root>
TypeError: _this7.createTwoChains(...) is not a function
    at newChildProps.on.blur (https://zx4kknz8jm.codesandbox.io/node_modules/ant-design-vue/lib/vc-trigger/Trigger.js:655:41)

    at invokeWithErrorHandling (https://zx4kknz8jm.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:1859:26)

    at HTMLInputElement.invoker (https://zx4kknz8jm.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:2184:14)

    at HTMLInputElement.original._wrapper (https://zx4kknz8jm.codesandbox.io/node_modules/vue/dist/vue.common.dev.js:7537:25)
```

This is due to that the wrapped tooltip input will cause `this.childOriginEvents[event]` be array of functions.

**Comment by tangjinzhou** [comment]
The reason is that the tooltip nested input.
We will optimize later.
Now you can add extra tags to solve it.
like: https://codesandbox.io/s/j29xovrkp9

**Comment by op13op** [comment]
Thanks for the help. It does work.
