### ISSUE TITLE
点击按钮，弹出确认modal，点击确认后延时0-200弹出message，会报一个vue错误

### ISSUE THREAD

**Issue by feisuger** [vueComponent/ant-design-vue#7032]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.4

### Environment
win10，Google Chrome， vue3.3.4，"@vue/cli-service": "~5.0.0"

### Reproduction link
[https://www.antdv.com/components/modal-cn](https://www.antdv.com/components/modal-cn)

### Steps to reproduce
```
<template>
<a-button @click="test">test</a-button>
</template>

<script lang="ts" setup>
import {message, Modal} from 'ant-design-vue';

async function test() {
await new Promise(resolve => {
Modal.confirm({
title: 'test',
onOk: async () => {
resolve(true);
},
onCancel: async () => {
resolve(true);
},
});
});
//当不使用setTimeout或者延时弹出消息直接写在上面的onOk中都不报错
//按如下写法，延时时间较长时也不报错，延时时间大概在0-200时会报错
setTimeout(() => {
message.open({type: 'success', content: 'test'});
});
}
</script>

<style lang="scss" scoped>

</style>
```

### What is expected?
希望开发环境也不要报错，同时解释下什么原有造成的，ant-design-vue3.x是没有这个问题的，4.0.3，4.0.4都有这个问题

### What is actually happening?

当不使用setTimeout时或者延时弹出消息直接写在上面的onOk中都不报错，延时时间较长时也不报错，延时时间在0-200时会报错
在开发环境报运行时vue错误
Uncaught runtime errors:

ERROR
Cannot read properties of null (reading 'insertBefore')
TypeError: Cannot read properties of null (reading 'insertBefore')
at insert (webpack-internal:///./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js:171:12)
at processCommentNode (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4658:7)
at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4617:9)
at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5134:9)
at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:196:19)
at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5164:51)
at updateComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5007:18)
at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4954:7)
at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4633:11)
at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5134:9)

**Comment by likui628** [comment]
[sandbox](https://codesandbox.io/s/zi-ding-yi-zi-duan-ant-design-vue-4-0-3-forked-nhh9sk?file=/src/demo.vue)

**Comment by feisuger** [comment]
> [sandbox](https://codesandbox.io/s/zi-ding-yi-zi-duan-ant-design-vue-4-0-3-forked-nhh9sk?file=/src/demo.vue) 看这个报错的信息应该个antdv没什么关系

也不能说完全没关系，因为3.x版本是没有这个问题的，我猜测是因为4.x版本改了全局modal的创建和销毁逻辑，具体是关闭弹窗时其内部调用了confirmDialogInstance.component.update();后报这个vue错误，如果可以能解释下是什么原因造成的吗

**Comment by nsnans** [comment]
在Notification里面使用了i8n配置提示信息，第一次提示后也出现了这个报错。后面再操作，提示后不会出现这个报错了

**Comment by feisuger** [comment]
> 在Notification里面使用了i18n配置提示信息，第一次提示后也出现了这个报错。后面再操作，提示后不会出现这个报错了

是的，这个错误报过一次后就不会再有了，除非再刷新页面，4.x版本更新的弹窗和抽屉用起来有明显卡顿，还有一些不知名问题

**Comment by gulewei** [comment]
我也遇到这个问题，看起来是两个组件上下文没有做好隔离，希望官方确认下

**Comment by 1024-lab** [comment]
同理也遇到了同样的问题，第一次报错，第二次就有问题了

**Comment by AKclown** [comment]
同理也遇到了同样的问题，第一次报错，第二次就没有问题了； antd 版本，4.0.7

**Comment by wsxe9988** [comment]
> 同理也遇到了同样的问题，第一次报错，第二次就没有问题了； antd 版本，4.0.7

更新至4.1.2
