### ISSUE TITLE
a-menu mode='horizontal' 当menu宽度小于父容器宽度时报错

### ISSUE THREAD

**Issue by YvesChen** [vueComponent/ant-design-vue#7055]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
nuxt3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/angry-wind-39f93p?file=%2Fpackage.json%3A5%2C15)

### Steps to reproduce
a-menu mode="horizontal" 只要改变宽度的时候，menu 重新计算布局时就会报错 ！！！⚠️⚠️⚠️一定要在 ssr模式下看
![image](https://github.com/vueComponent/ant-design-vue/assets/5573829/b098e572-da5d-48b0-870c-98c5dc6cd443)

### What is expected?
当屏幕宽度缩放时，会报错

### What is actually happening?

````
[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'toLowerCase')
````
或者
````
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'namespaceURI')
at isSVGContainer (chunk-D3I6P6U6.js:5914:58)
at hydrateNode (chunk-D3I6P6U6.js:6069:13)
at hydrateSubTree (chunk-D3I6P6U6.js:7134:13)
at ReactiveEffect.componentUpdateFn [as fn] (chunk-D3I6P6U6.js:7154:13)
at ReactiveEffect.run (chunk-D3I6P6U6.js:452:19)
at instance.update (chunk-D3I6P6U6.js:7273:52)
at setupRenderEffect (chunk-D3I6P6U6.js:7281:5)
at mountComponent (chunk-D3I6P6U6.js:7071:5)
at processComponent (chunk-D3I6P6U6.js:7024:9)
at patch (chunk-D3I6P6U6.js:6497:11)
````

**Comment by YvesChen** [comment]
@tangjinzhou 只有在新建的 nuxt3 会遇到这种情情况！vue3新建的项目不会出现这种情况！

**Comment by YvesChen** [comment]
#4833 此问题也一直未得到解决，不清楚是 nuxt3问题，还是 ant 的问题
