### ISSUE TITLE
There was a problem in version 4.x

### ISSUE THREAD

**Issue by gusto-dev** [vueComponent/ant-design-vue#7173]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
vue3, webpack5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/type-ant-design-vue-4-0-7-l572zc?file=%2Fsrc%2FApp.vue)

### Steps to reproduce
I clicked the normal button.

### What is expected?
nothing happens

### What is actually happening?
Compiled with problems:

ERROR
Cannot read properties of undefined (reading 'value')
TypeError: Cannot read properties of undefined (reading 'value')
at ReactiveEffect.eval [as fn] (webpack-internal:///./.yarn/__virtual__/ant-design-vue-virtual-e74f6a7eeb/0/cache/ant-design-vue-npm-4.0.7-431f0949db-f03a746faf.zip/node_modules/ant-design-vue/es/config-provider/hooks/useConfigInject.js:72:83)
at ReactiveEffect.run (webpack-internal:///./.yarn/cache/@vue-reactivity-npm-3.2.47-1182f7aa47-bd61134e4b.zip/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:225:19)
at get value [as value] (webpack-internal:///./.yarn/cache/@vue-reactivity-npm-3.2.47-1182f7aa47-bd61134e4b.zip/node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:1157:33)
at showWave (webpack-internal:///./.yarn/__virtual__/ant-design-vue-virtual-e74f6a7eeb/0/cache/ant-design-vue-npm-4.0.7-431f0949db-f03a746faf.zip/node_modules/ant-design-vue/es/_util/wave/useWave.js:13:21)
at HTMLButtonElement.onClick (webpack-internal:///./.yarn/__virtual__/ant-design-vue-virtual-e74f6a7eeb/0/cache/ant-design-vue-npm-4.0.7-431f0949db-f03a746faf.zip/node_modules/ant-design-vue/es/_util/wave/index.js:60:13)

---
As in the link above, the same error occurs in codesandbox.

**Comment by selicens** [comment]
The solution is to downgrade a small version and wait for the next version to fix it

**Comment by kovsu** [comment]
fixed in 4.0.8
