### ISSUE TITLE
4.0.7升级4.0.8后页面无法显示，出现cssinjs死循环问题

### ISSUE THREAD

**Issue by mfish-qf** [vueComponent/ant-design-vue#7203]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
windows11,edge114.0.1823.55，vue3.3.12

### Reproduction link
[https://www.antdv.com/docs/vue/changelog-cn](https://www.antdv.com/docs/vue/changelog-cn)

### Steps to reproduce
- 4.0.7升级4.0.8
- pnpm run dev启动项目
- 访问项目路径

### What is expected?
页面正常打开

## F12报以下错误
```
main.ts:43  [Vue warn]: Unhandled error during execution of watcher callback
at <AConfigProvider locale= Object theme= Object >
at <App>
warn2 @ runtime-core.esm-bundler.js:41
await in warn2(异步)
(匿名) @ main.ts:43
setTimeout(异步)
(匿名) @ __uno.css:19
(匿名) @ __uno.css:19
util.js:13  Uncaught (in promise) RangeError: Maximum call stack size exceeded
at [Symbol.hasInstance] (<anonymous>)
at util.js:13:11
at Array.forEach (<anonymous>)
at flattenToken (util.js:10:24)
at util.js:16:16
at Array.forEach (<anonymous>)
at flattenToken (util.js:10:24)
at util.js:16:16
at Array.forEach (<anonymous>)
at flattenToken (util.js:10:24)
```

**Comment by aibayanyu20** [comment]
有没有复现？
![image](https://github.com/vueComponent/ant-design-vue/assets/45655660/69e0e564-105e-488c-b280-2fc79b5fc1a5)
可以zhengc正常打开呢？

**Comment by mfish-qf** [comment]
> 有没有复现？ 可以zhengc正常打开呢？ ![图像](https://private-user-images.githubusercontent.com/45655660/291486895-69e0e564-105e-488c-b280-2fc79b5fc1a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5ODgzNjIsIm5iZiI6MTcwMjk4ODA2MiwicGF0aCI6Ii80NTY1NTY2MC8yOTE0ODY4OTUtNjllMGU1NjQtMTA1ZS00ODhjLWIyODAtMmZjNzliNWZjMWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDEyMTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MTVjNTA3YTgxMzc5Y2U3NWZkZGZlMjM0YzQ0MzQ3NzgyZTkzNjYwY2ZiYzEwZWQ0ODAwYzAxZWU2YjNlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0xFj5kAATKWRVpg-Lfggt_0X2i0YT5ZXXrXTUuHuo04)

不是这个地址，是我自己的项目升级以后无法正常打开。降回4.0.7就好了

**Comment by aibayanyu20** [comment]
搞一个最小复现出来吧，没复现没办法排查问题呢

**Comment by mfish-qf** [comment]
> 搞一个最小复现出来吧，没复现没办法排查问题呢
我发了生产环境，地址如下：直接登录即可
http://app.mfish.com.cn:11119/
F12里面有个错误信息，你可以参考下。。生产环境能进去，但是颜色好像有问题。

**Comment by aibayanyu20** [comment]
生产环境没法排查问题呢？

**Comment by mfish-qf** [comment]
> 生产环境没法排查问题呢？

![image](https://github.com/vueComponent/ant-design-vue/assets/22856757/4d41858b-a033-47de-a187-0784558621a1)
这个方法死循环

**Comment by aibayanyu20** [comment]
要排查哪里造成的死循环，这里不是根本原因

**Comment by mfish-qf** [comment]
> 要排查哪里造成的死循环，这里不是根本原因

跟取Theme有点关系，我只能排查到这了。。
我这项目东西太多，不太好搭复现环境

**Comment by aibayanyu20** [comment]
> > 要排查哪里造成的死循环，这里不是根本原因
> 
> 跟取Theme有点关系，我只能排查到这了。。 我这项目东西太多，不太好搭复现环境

抱歉，我跑了一下我们的pro项目并没有复现你的问题，你可以考虑看看如何提交一个在线的最小复现，不然我也是无能为力

**Comment by mfish-qf** [comment]
> > > 要排查哪里造成的死循环，这里不是根本原因
> > 
> > 
> > 跟取Theme有点关系，我只能排查到这了。。 我这项目东西太多，不太好搭复现环境
> 
> 抱歉，我跑了一下我们的pro项目并没有复现你的问题，你可以考虑看看如何提交一个在线的最小复现，不然我也是无能为力

我好像找到原因了，token中颜色设置computed计算属性时，会出现这个问题。你试下看看
token: {
      colorPrimary:computed(() => .....)
}

**Comment by aibayanyu20** [comment]
正常来说不允许这样使用的之前是实现了一个toReactive，自动帮你解ref，但是会存在一些其他的响应式的问题，应该是整个的theme是一个响应式的对象才是正确的

**Comment by mfish-qf** [comment]
> 正常来说不允许这样使用的之前是实现了一个toReactive，自动帮你解ref，但是会存在一些其他的响应式的问题，应该是整个的theme是一个响应式的对象才是正确的

好的。。找到问题了，我自己想办法改吧

**Comment by mfish-qf** [comment]
> 正常来说不允许这样使用的之前是实现了一个toReactive，自动帮你解ref，但是会存在一些其他的响应式的问题，应该是整个的theme是一个响应式的对象才是正确的

已解决
